{
 "title": "AWS DynamoDB CloudWatch",
 "description": "AWS DynamoDB CloudWatch metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "query": {}
   },
   {
    "name": "period",
    "label": "Period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "table",
    "label": "Table",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Account",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors (${period})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "UserErrors",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Usage (${period})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "Class": "None", "Resource": "*", "Service": "DynamoDB", "Type": "Resource" },
       "metricName": "ResourceCount",
       "namespace": "AWS/Usage",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Reads (${period})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "AccountMaxReads",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "metricName": "AccountMaxTableLevelReads",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "metricName": "AccountProvisionedReadCapacityUtilization",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "metricName": "MaxProvisionedTableReadCapacityUtilization",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Writes (${period})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "AccountMaxWrites",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "metricName": "AccountMaxTableLevelWrites",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "metricName": "AccountProvisionedWriteCapacityUtilization",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "metricName": "MaxProvisionedTableWriteCapacityUtilization",
       "namespace": "AWS/DynamoDB",
       "period": "${period}",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Errors (${period})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throttling (${period})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "*"
     },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "*"
     },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "*"
     },
     "metricName": "OnlineIndexThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Requests Count (${period})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Requests Durations (${period})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Reads (${period})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ConditionalCheckFailedRequests",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "OnDemandMaxReadRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "ReturnedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Writes (${period})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "OnDemandMaxWriteRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ProvisionedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "TimeToLiveDeletedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "TransactionConflict",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Table: ${table}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "table" },
  {
   "title": "Errors (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throttling (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnlineIndexThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Successful Requests Count (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Successful Requests Durations (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Reads (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ConditionalCheckFailedRequests",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "OnDemandMaxReadRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "ReturnedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Writes (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "OnDemandMaxWriteRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ProvisionedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "TimeToLiveDeletedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "TransactionConflict",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Global Secondary Index: ${table}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "table"
  },
  {
   "title": "Global Secondary Indexes Reads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnDemandMaxReadRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Global Secondary Indexes Writes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnDemandMaxWriteRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnlineIndexConsumedWriteCapacity",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnlineIndexPercentageProgress",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "PendingReplicationCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "DynamoDB Streams: ${table}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }, "repeat": "table" },
  {
   "title": "DynamoDB Stream",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "StreamLabel": "*", "TableName": "${table}" },
     "metricName": "ReturnedBytes",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "Operation": "*", "StreamLabel": "*", "TableName": "${table}" },
     "metricName": "ReturnedRecordsCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "DynamoDB Stream Durations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "StreamLabel": "*", "TableName": "${table}" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Kinesis Data Streams: ${table}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }, "repeat": "table" },
  {
   "title": "Kinesis Data Stream",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DelegatedOperation": "*", "TableName": "${table}" },
     "metricName": "AgeOfOldestUnreplicatedRecord",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DelegatedOperation": "*", "TableName": "${table}" },
     "metricName": "ConsumedChangeDataCaptureUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DelegatedOperation": "*", "TableName": "${table}" },
     "metricName": "FailedToReplicateRecordCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DelegatedOperation": "*", "TableName": "${table}" },
     "metricName": "ThrottledPutRecordCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Global Table: ${table}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 }, "repeat": "table" },
  {
   "title": "Global Table",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ReceivingRegion": "*", "TableName": "${table}" },
     "metricName": "ReplicationLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}